apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "3000"
  MONGODB_URI: "mongodb+srv://Himanshuraw:81mansh0@freecluster.bvcym.mongodb.net/?retryWrites=true&w=majority&appName=FreeCluster"
  SALT_ROUNDS: "10"
  JWT_SECRET: "secretnottobeshared"
  ML_SERVICE_URL: "http://ml-service:8000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
data:
  .env: |
    MONGODB_URI=mongodb+srv://Himanshuraw:81mansh0@freecluster.bvcym.mongodb.net/?retryWrites=true&w=majority&appName=FreeCluster
    DATA_PATH=./data/transformed_data.csv
    MODEL_DIR=./models

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json_lines
      }
    }

    filter {
      date {
        match => [ "timestamp", "ISO8601" ]
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }