---
- name: Deploy using Kubernetes
  hosts: local
  become: yes

  vars_files:
    - vault.yml

  vars:
    k8s_dir: "{{ playbook_dir }}/../k8s"
    kubeconfig_path: "{{ kubeconfig_path | default('/home/' + ansible_user + '/.kube/config')"
    manifest_order:
      - secrets.yaml
      - configmaps.yml
      - pv.yaml
      - ml_service.yml
      - backend.yml
      - frontend.yml
      - logstash.yml
      - elasticsearch.yml
      - kibana.yml

  roles:
    - k8s
