- name: Install Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: "0755"

- name: Ensure kubeconfig directory exists
  file:
    path: "{{ kubeconfig_path | dirname }}"
    state: directory
    mode: "0755"

- name: Apply Kubernetes manifests in order
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ k8s_dir }}/{{ item }}"
  loop: "{{ manifest_order }}"
  loop_control:
    label: "{{ item }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
